### ISSUE TITLE
tensorflow_gpu 2.1 and dependencies

### ISSUE THREAD

**Issue by pepper-jk** [tensorflow/federated#827]
**Description of the bug**
When I install tensorflow federated after tensorflow gpu, tensorflow will no longer recognize the GPU. I have a simple script using `tf.test.gpu_device_name())` to test if a gpu is available, but it complained about missing libs: 'libnvinfer.so.6', 'libnvinfer_plugin.so.6', and 

After a little digging I found out that the libs `libcudnn7` and `libnvinfer6` were not installed or at least not in the right version to match cuda 10.0 so I downgraded them.

However it looks like 'libcufft.so.10', 'libcurand.so.10', 'libcusolver.so.10' and 'libcusparse.so.10' are missing.

What dependency did I miss?

Is downgrading the only solution?

Should I instead upgrade to cuda 10.1 or even 10.2?

**Environment:**
* OS: Linux Ubuntu 16.04
* Python package versions:
  * fensorflow_federated 0.13.1
  * tensorflow 2.1.0
  * Tensorflow_gpu 2.1.0
* Python version: 3.6.3
* CUDA/cuDNN version:
  * Driver Version: 410.129
  * CUDA Version: 10.0
  * libcudnn7 version: 7.6.4.38-1+cuda10.0
  * libnvinfer6 version: 6.0.1-1+cuda10.0
* What TensorFlow Federated execution stack are you using? I'm not sure about this question

**output**
first output from my script:
```
2020-04-14 16:44:56.772603: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda-10.2/lib64:/usr/local/cuda-10.1/lib64:/usr/local/cuda-10.0/lib64:/usr/local/cuda-10.0/extras/CUPTI/lib64
2020-04-14 16:44:56.772704: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda-10.2/lib64:/usr/local/cuda-10.1/lib64:/usr/local/cuda-10.0/lib64:/usr/local/cuda-10.0/extras/CUPTI/lib64
2020-04-14 16:44:56.772717: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2020-04-14 16:44:57.378167: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-04-14 16:44:57.396282: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3000285000 Hz
2020-04-14 16:44:57.400402: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x497f900 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-04-14 16:44:57.400453: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-04-14 16:44:57.405387: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-04-14 16:44:59.734901: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x4a389b0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-04-14 16:44:59.734975: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Tesla K40m, Compute Capability 3.5
2020-04-14 16:44:59.736434: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:82:00.0 name: Tesla K40m computeCapability: 3.5
coreClock: 0.745GHz coreCount: 15 deviceMemorySize: 11.17GiB deviceMemoryBandwidth: 268.58GiB/s
2020-04-14 16:44:59.736850: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-04-14 16:44:59.739934: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-04-14 16:44:59.740102: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcufft.so.10'; dlerror: libcufft.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda-10.2/lib64:/usr/local/cuda-10.1/lib64:/usr/local/cuda-10.0/lib64:/usr/local/cuda-10.0/extras/CUPTI/lib64
2020-04-14 16:44:59.740237: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcurand.so.10'; dlerror: libcurand.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda-10.2/lib64:/usr/local/cuda-10.1/lib64:/usr/local/cuda-10.0/lib64:/usr/local/cuda-10.0/extras/CUPTI/lib64
2020-04-14 16:44:59.740363: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcusolver.so.10'; dlerror: libcusolver.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda-10.2/lib64:/usr/local/cuda-10.1/lib64:/usr/local/cuda-10.0/lib64:/usr/local/cuda-10.0/extras/CUPTI/lib64
2020-04-14 16:44:59.740485: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcusparse.so.10'; dlerror: libcusparse.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda-10.2/lib64:/usr/local/cuda-10.1/lib64:/usr/local/cuda-10.0/lib64:/usr/local/cuda-10.0/extras/CUPTI/lib64
2020-04-14 16:44:59.747440: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-04-14 16:44:59.747473: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1592] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2020-04-14 16:44:59.747509: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1096] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-04-14 16:44:59.747526: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102]      0 
2020-04-14 16:44:59.747540: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] 0:   N 
No GPU found
```

I downgraded the libs like this:
```
sudo apt-get install --no-install-recommends cuda-10-0 libcudnn7=7.6.4.38-1+cuda10.0 libcudnn7-dev=7.6.4.38-1+cuda10.0 libnvinfer6=6.0.1-1+cuda10.0 libnvinfer-dev=6.0.1-1+cuda10.0 libnvinfer-plugin6=6.0.1-1+cuda10.0
```

After downgrading the libs I got this:
```
2020-04-15 16:58:51.794868: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2020-04-15 16:58:52.126343: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.6
WARNING:tensorflow:From gpu_test.py:6: is_gpu_available (from tensorflow.python.framework.test_util) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
2020-04-15 16:58:53.077338: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-04-15 16:58:53.093169: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3000285000 Hz
2020-04-15 16:58:53.098709: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x4136490 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-04-15 16:58:53.098763: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-04-15 16:58:53.105241: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-04-15 16:58:53.301034: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x41ef140 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-04-15 16:58:53.301114: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Tesla K40m, Compute Capability 3.5
2020-04-15 16:58:53.302911: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:82:00.0 name: Tesla K40m computeCapability: 3.5
coreClock: 0.745GHz coreCount: 15 deviceMemorySize: 11.17GiB deviceMemoryBandwidth: 268.58GiB/s
2020-04-15 16:58:53.303556: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-04-15 16:58:53.307593: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-04-15 16:58:53.307836: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcufft.so.10'; dlerror: libcufft.so.10: cannot open shared object file: No such file or directory
2020-04-15 16:58:53.307972: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcurand.so.10'; dlerror: libcurand.so.10: cannot open shared object file: No such file or directory
2020-04-15 16:58:53.308097: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcusolver.so.10'; dlerror: libcusolver.so.10: cannot open shared object file: No such file or directory
2020-04-15 16:58:53.308217: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcusparse.so.10'; dlerror: libcusparse.so.10: cannot open shared object file: No such file or directory
2020-04-15 16:58:53.308285: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-04-15 16:58:53.308304: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1592] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2020-04-15 16:58:53.308338: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1096] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-04-15 16:58:53.308356: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102]      0 
2020-04-15 16:58:53.308371: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] 0:   N 
No GPU found
[...]
```

**Expected behavior**
-

**Additional context**
Downgrading to tensorflow_gpu==2.0 fixed the issue, but then I would also have to downgrade to tensorflow_federated==0.11.0 and for our project we need at least version 0.12.0.

**Comment by michaelreneer** [comment]
Hi @pepper-jk, thanks for your interest in TensorFlow Federated.

So this is interesting. Note that [tensorflow](https://pypi.org/project/tensorflow/) and [tensorflow-gpu](https://pypi.org/project/tensorflow-gpu/) have different project names. But they both function as the `tensorflow` package when you install them into the same environment. Also note that the `tf-nightly` behaves this way as well. This is supposed to be a feature of Python, but it can be confusing.

I think that you simply no longer need to install `tensorflow_gpu` given the instructions found here https://www.tensorflow.org/install/gpu. Can you try uninstalling this package or creating a new environment without it and try and re-run your TFF code.

**Comment by pepper-jk** [comment]
Thanks for the quick answer.

**Disclaimer**
I can't 100% reproduce the issue at the moment, since the server I'm working on is used by other users at the moment and apparently they use different lib versions (see below). So do not take this as the final reply to your comment. Just wanted to let you know, I'm here and greatefull for your support.

However I still get a similar issue with a "clean" venv with just tf_federated installed:
```
2020-04-16 19:01:03.248229: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2020-04-16 19:01:03.248547: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvrtc.so.10.2: cannot open shared object file: No such file or directory
2020-04-16 19:01:03.248561: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2020-04-16 19:01:04.009028: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-04-16 19:01:04.013507: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:82:00.0 name: Tesla K40m computeCapability: 3.5
coreClock: 0.745GHz coreCount: 15 deviceMemorySize: 11.17GiB deviceMemoryBandwidth: 268.58GiB/s
2020-04-16 19:01:04.013689: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-04-16 19:01:04.013731: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-04-16 19:01:04.013786: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcufft.so.10'; dlerror: libcufft.so.10: cannot open shared object file: No such file or directory
2020-04-16 19:01:04.013837: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcurand.so.10'; dlerror: libcurand.so.10: cannot open shared object file: No such file or directory
2020-04-16 19:01:04.013884: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcusolver.so.10'; dlerror: libcusolver.so.10: cannot open shared object file: No such file or directory
2020-04-16 19:01:04.013930: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcusparse.so.10'; dlerror: libcusparse.so.10: cannot open shared object file: No such file or directory
2020-04-16 19:01:04.013956: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-04-16 19:01:04.013964: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1592] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
No GPU found
```

the current library versions changed to:
* libcudnn7 version: 7.6.5.32-1+cuda10.2
* libnvinfer6 version: 6.0.1-1+cuda10.2

**Comment by michaelreneer** [comment]
@pepper-jk Have you gone through all the GPU installation steps found at https://www.tensorflow.org/install/gpu?

**Comment by pepper-jk** [comment]
No, since I did not set up the driver and cuda.

My job was to setup the libraries, but I got permission to fix the installation. I will do so tomorrow.

**Comment by michaelreneer** [comment]
It seems possible that we updated the TF that you were using and thus you need to update the cuda library. I think you should install the software here https://www.tensorflow.org/install/gpu#software_requirements and then follow the instructions for linux setup here https://www.tensorflow.org/install/gpu#linux_setup

**Comment by pepper-jk** [comment]
Yes, that would be the ideal solution. However I do not have green light yet to change the cuda version on the server, or the driver for that matter.

Once I get the green light I'll happily do that.

Regarding [your earlier post](https://github.com/tensorflow/federated/issues/827#issuecomment-614772302) about the fresh venv. I was able to downgrade the packages again and even with a "clean" venv, I get the same errors (see output below).

Which library does contain the shared libs `libcufft.so.10`, `libcurand.so.10`, `libcusolver.so.10`, and `libcusparse.so.10`?

Or do they only come with newer versions of cuda and its libraries?

output:
```
2020-04-17 08:44:10.129937: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2020-04-17 08:44:10.131621: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.6
2020-04-17 08:44:10.830622: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-04-17 08:44:10.834524: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:82:00.0 name: Tesla K40m computeCapability: 3.5
coreClock: 0.745GHz coreCount: 15 deviceMemorySize: 11.17GiB deviceMemoryBandwidth: 268.58GiB/s
2020-04-17 08:44:10.834739: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-04-17 08:44:10.836352: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-04-17 08:44:10.836481: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcufft.so.10'; dlerror: libcufft.so.10: cannot open shared object file: No such file or directory
2020-04-17 08:44:10.836534: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcurand.so.10'; dlerror: libcurand.so.10: cannot open shared object file: No such file or directory
2020-04-17 08:44:10.836585: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcusolver.so.10'; dlerror: libcusolver.so.10: cannot open shared object file: No such file or directory
2020-04-17 08:44:10.836633: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcusparse.so.10'; dlerror: libcusparse.so.10: cannot open shared object file: No such file or directory
2020-04-17 08:44:10.836659: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-04-17 08:44:10.836668: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1592] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
No GPU found
```

**Comment by pepper-jk** [comment]
> It seems possible that we updated the TF that you were using and thus you need to update the cuda library. I think you should install the [software requirements](https://www.tensorflow.org/install/gpu#software_requirements) and then follow the instructions to [setup linux](https://www.tensorflow.org/install/gpu#linux_setup).

Thanks for the help.

I followed the instructions and now it works perfectly.

```
$ python gpu_test.py            
2020-04-20 15:52:20.236822: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2020-04-20 15:52:20.439014: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.6
2020-04-20 15:52:26.833957: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-04-20 15:52:29.211652: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:82:00.0 name: Tesla K40m computeCapability: 3.5
coreClock: 0.745GHz coreCount: 15 deviceMemorySize: 11.17GiB deviceMemoryBandwidth: 268.58GiB/s
2020-04-20 15:52:29.211765: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-04-20 15:52:29.211873: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-04-20 15:52:29.286326: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-04-20 15:52:29.325932: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-04-20 15:52:29.810698: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-04-20 15:52:29.858476: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-04-20 15:52:29.858591: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-04-20 15:52:29.861818: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0
GPU found
```

## For future reference:

Please note that installing the `cude-10-1` package on ubuntu 16.04 will require a newer driver than `nvidia-418`, whiche the guide promotes, I assume it is the newest. In my case that was `nvidia-440` However apt will automatically install it an remove the old driver you just installed with the guide.

Also in `nvidia-smi` it shows cuda version 10.2 for some reason. I'm assuming one could just install the newest cuda version available and it would still work, even though both [the guide](https://www.tensorflow.org/install/gpu#linux_setup) and  [tensorflows website](https://www.tensorflow.org/install/source#tested_build_configurations#Linux#GPU) states that cuda 10.1 is the only officially supported version.

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.64.00    Driver Version: 440.64.00    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K40m          Off  | 00000000:82:00.0 Off |                    0 |
| N/A   40C    P0    67W / 235W |      0MiB / 11441MiB |     94%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

`apt` also states that Cuda 10.1 is installed:

```
$ sudo apt-cache policy cuda-10-1
cuda-10-1:
  Installed: 10.1.243-1
  Candidate: 10.1.243-1
  Version table:
 *** 10.1.243-1 500
        500 http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Packages
        100 /var/lib/dpkg/status
     10.1.168-1 500
        500 http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Packages
     10.1.105-1 500
        500 http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Packages
$ sudo apt-cache policy cuda-10-2
cuda-10-2:
  Installed: (none)
  Candidate: 10.2.89-1
  Version table:
     10.2.89-1 500
        500 http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Packages
```
